import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, BadgeCheck, BookOpenCheck, CalendarDays, MapPin, Search, ShieldCheck, SlidersHorizontal, Star } from 'lucide-react';
import { PublicDialog, PublicFooter, PublicHeader, SectionHead } from './PublicChrome.jsx';
import { DemoLink, MapPreview, PublicTutorCard } from './PublicPieces.jsx';
import { photo, publicTutors } from '../../data/public.js';
import useDemoStorage from '../../hooks/useDemoStorage.js';

const needs = [
  ['01', 'Củng cố kiến thức', 'Lấp phần kiến thức còn hổng và học lại theo nhịp dễ hiểu hơn.', 'Toán', 'blue'],
  ['02', 'Nâng điểm trên lớp', 'Ôn đúng trọng tâm, luyện bài đều và theo sát tiến độ ở trường.', 'Tiếng Anh', 'red'],
  ['03', 'Chuẩn bị kỳ thi', 'Lập kế hoạch học rõ ràng theo mục tiêu và thời gian còn lại.', 'Ngữ văn', 'yellow'],
  ['04', 'Học theo mục tiêu riêng', 'Chọn gia sư phù hợp với mục tiêu ngoại ngữ hoặc kỹ năng cụ thể.', 'Vật lý', 'cyan'],
];

export default function LearnerLanding() {
  const navigate = useNavigate();
  const [subject, setSubject] = useState('Tất cả môn');
  const [area, setArea] = useState('Tất cả khu vực');
  const [time, setTime] = useState('Mọi khung giờ');
  const [budget, setBudget] = useState('Mọi mức phí');
  const [sort, setSort] = useState('recommended');
  const [saved, setSaved] = useDemoStorage('tnm.savedTutors', []);
  const [dialog, setDialog] = useState(null);
  const showTutor = (item, text) => setDialog({ title: item.name, text, tutorId: item.id });
  const toggleSave = (id) => setSaved((ids) => ids.includes(id) ? ids.filter((x) => x !== id) : [...ids, id]);
  const filtered = useMemo(() => publicTutors.filter((t) => (subject === 'Tất cả môn' || t.subject === subject) && (area === 'Tất cả khu vực' || t.area === area) && (time === 'Mọi khung giờ' || t.time === time) && (budget === 'Mọi mức phí' || t.fee <= Number(budget))).sort((a,b) => sort === 'price' ? a.fee-b.fee : sort === 'rating' ? b.rating-a.rating : publicTutors.indexOf(a)-publicTutors.indexOf(b)), [subject,area,time,budget,sort]);
  const apply = () => document.getElementById('tutors')?.scrollIntoView({ behavior: 'smooth' });
  return <div className="public-page public-page--learner"><PublicHeader kind="learner" onInfo={(title,text) => setDialog({title,text})}/><main>
    <section className="public-hero public-hero--learner"><div className="public-wrap public-hero__grid"><div className="public-hero__copy"><span className="public-hero__eyebrow">TUTORNEARME · HỌC GẦN HƠN, HIỂU NHAU HƠN</span><h1>Bạn đau đầu để<br/>tìm gia sư tốt,<br/><em>TutorNearMe<br/>sẽ giúp bạn.</em></h1><p>Tìm sinh viên gia sư theo đúng môn, khu vực, thời gian rảnh và mức phí gia đình mong muốn — tất cả trong một trải nghiệm rõ ràng, dễ so sánh.</p><div className="public-hero__actions"><a className="public-btn public-btn--yellow" href="#finder">Tìm gia sư phù hợp <ArrowRight size={18}/></a><a className="public-hero__text-link" href="#how">Xem cách hoạt động ↘</a></div></div><div className="public-hero__visual"><img className="public-hero__photo-main" src={photo.learnerHero} alt="Học sinh học tập cùng bạn bè"/><img className="public-hero__photo-side" src={photo.learnerSide} alt="Gia sư đang hướng dẫn bài học"/><span className="public-float public-float--yellow"><b>Gần bạn</b><small>ưu tiên khu vực phù hợp</small></span><span className="public-float public-float--location"><b>4.9/5</b><small>đánh giá demo</small></span></div></div></section>
    <section className="public-section public-learner-finder" id="finder"><div className="public-wrap"><div className="public-finder__intro"><div><span className="public-kicker">TÌM THEO ĐIỀU QUAN TRỌNG NHẤT</span><h2>Cho TutorNearMe biết bạn đang cần gì.</h2></div><p>Môn học · khu vực · lịch rảnh · mức phí. Lọc nhanh trước khi so sánh hồ sơ.</p></div><div className="public-finder__fields public-finder__fields--four"><label>Môn học<select value={subject} onChange={(e) => setSubject(e.target.value)}><option>Tất cả môn</option>{publicTutors.map(t => <option key={t.subject}>{t.subject}</option>)}</select></label><label>Khu vực<select value={area} onChange={(e) => setArea(e.target.value)}><option>Tất cả khu vực</option>{publicTutors.map(t => <option key={t.area}>{t.area}</option>)}</select></label><label>Lịch rảnh<select value={time} onChange={(e) => setTime(e.target.value)}><option>Mọi khung giờ</option><option>Buổi chiều</option><option>Buổi tối</option><option>Cuối tuần</option></select></label><label>Mức phí<select value={budget} onChange={(e) => setBudget(e.target.value)}><option>Mọi mức phí</option><option value="180000">Đến 180.000đ</option><option value="220000">Đến 220.000đ</option></select></label><button className="public-btn public-btn--blue" onClick={apply}><Search size={18}/> Tìm gia sư</button></div></div></section>
    <section className="public-section public-learner-needs" id="needs"><div className="public-wrap"><SectionHead kicker="BẮT ĐẦU TỪ NHU CẦU THẬT" title="Hôm nay bạn muốn cải thiện điều gì?"/><div className="public-learner-needs__grid">{needs.map(([n,title,desc,preset,tone]) => <button type="button" className={`public-learner-need tone-${tone}`} key={n} onClick={() => { setSubject(preset); apply(); }}><span>{n}</span><h3>{title}</h3><p>{desc}</p><ArrowRight size={20}/></button>)}</div></div></section>
    <section className="public-section public-learner-tutors" id="tutors"><div className="public-wrap"><div className="public-results-head"><SectionHead kicker="GIA SƯ PHÙ HỢP VỚI BẠN" title="Học cùng người truyền cảm hứng." text="So sánh môn học, khu vực, lịch rảnh và mức phí trước khi kết nối."/><div className="public-results-head__tools"><span>{filtered.length} gia sư phù hợp</span><label><SlidersHorizontal size={16}/> Sắp xếp<select value={sort} onChange={(e) => setSort(e.target.value)}><option value="recommended">Gợi ý</option><option value="rating">Đánh giá</option><option value="price">Mức phí thấp</option></select></label></div></div>{filtered.length ? <div className="public-tutor-grid">{filtered.map((t) => <PublicTutorCard key={t.id} tutor={t} to={`/tutors/${t.id}`} saved={saved.includes(t.id)} onSave={toggleSave} onOpen={(item) => showTutor(item, `${item.bio} ${item.university}. Học phí minh họa ${new Intl.NumberFormat('vi-VN').format(item.fee)}đ/buổi.`)}/>)}</div> : <div className="public-empty"><Search size={30}/><h3>Chưa có gia sư khớp bộ lọc</h3><p>Thử đổi môn học, khu vực, lịch hoặc mức phí.</p><button className="public-btn public-btn--blue" onClick={() => { setSubject('Tất cả môn'); setArea('Tất cả khu vực'); setTime('Mọi khung giờ'); setBudget('Mọi mức phí'); }}>Xóa bộ lọc</button></div>}<div className="public-section__end"><DemoLink to="/learner/search" className="public-btn--outline-blue">Xem trang tìm kiếm đầy đủ</DemoLink></div></div></section>
    <section className="public-section public-confidence"><div className="public-wrap public-confidence__grid"><div><SectionHead kicker="VÌ SAO DỄ QUYẾT ĐỊNH HƠN?" title="Thông tin cần thiết được trình bày trước khi bạn gửi yêu cầu." text="TutorNearMe ưu tiên sự rõ ràng để gia đình không phải hỏi từng thông tin cơ bản." light/><a href="#tutors">Xem hồ sơ mẫu <ArrowRight size={18}/></a></div><div className="public-confidence__list"><span><BookOpenCheck/> Môn học & kinh nghiệm</span><span><CalendarDays/> Lịch rảnh phù hợp</span><span><MapPin/> Khu vực gần bạn</span><span><ShieldCheck/> Hồ sơ minh bạch</span></div></div></section>
    <section className="public-section public-map-section public-map-section--learner"><div className="public-wrap public-map-section__grid"><MapPreview tutors={publicTutors} onOpen={(item) => showTutor(item, `${item.subject} · ${item.area}. Vị trí chỉ biểu diễn ở mức khu vực trong prototype.`)}/><div><SectionHead kicker="TUTORNEARME MAP" title="Học gần hơn để duy trì lịch học nhẹ nhàng hơn." text="Với lớp trực tiếp, khu vực là một phần quan trọng của sự phù hợp. Chọn khu vực giúp thu hẹp phạm vi tìm kiếm."/><div className="public-privacy"><ShieldCheck size={21}/><span><strong>Tôn trọng riêng tư</strong><small>Prototype chỉ biểu diễn khu vực, không hiển thị địa chỉ nhà cụ thể.</small></span></div></div></div></section>
    <section className="public-section public-learner-how" id="how"><div className="public-wrap"><SectionHead kicker="MỘT LUỒNG RÕ RÀNG" title="Từ nhu cầu đến buổi học đầu tiên" text="Không cần vòng vo qua nhiều bước không cần thiết."/><div className="public-learner-how__grid">{[['1','Chọn điều bạn cần','Môn, khu vực, thời gian và ngân sách.'],['2','So sánh hồ sơ','Xem năng lực, lịch rảnh, phí và đánh giá.'],['3','Gửi yêu cầu học','Chia sẻ mục tiêu và khung giờ mong muốn.'],['4','Theo dõi & đánh giá','Xem trạng thái buổi học và phản hồi sau học.']].map(([n,t,d]) => <div key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
    <section className="public-section public-learner-offer" id="offers"><div className="public-wrap public-learner-offer__grid"><div><span className="public-kicker">QUYỀN LỢI KHI BẮT ĐẦU</span><h2>Đủ thông tin để thử một lựa chọn mà không bị áp lực.</h2><p>Xem và so sánh thông tin trước khi gửi yêu cầu học — không cần cam kết khi còn cân nhắc.</p><DemoLink to="/learner/search" className="public-btn--yellow">Bắt đầu khám phá</DemoLink></div><div className="public-learner-offer__seal"><BadgeCheck size={72}/><strong>Chọn rõ ràng.<br/>Học tự tin.</strong></div></div></section>
    <section className="public-section public-learner-stories" id="stories"><div className="public-wrap"><SectionHead kicker="GÓC PHỤ HUYNH & HỌC SINH" title="Những câu hỏi nên được trả lời trước khi chọn gia sư." text="Nội dung hỗ trợ quyết định tìm gia sư, gắn với nhu cầu học thật."/><div className="public-learner-stories__grid"><article className="public-learner-stories__feature"><img src={photo.story} alt="Học sinh học cùng gia sư" loading="lazy"/><div><span>HƯỚNG DẪN CHỌN GIA SƯ</span><h3>Nên nhìn vào điều gì ngoài điểm số và trường đại học?</h3><p>Một hồ sơ phù hợp còn nằm ở cách giao tiếp, lịch rảnh, mức phí và khả năng theo sát mục tiêu.</p><a href="#tutors">Xem hồ sơ mẫu →</a></div></article><article><CalendarDays size={28}/><span>LỊCH HỌC</span><h3>Lịch nào thực tế để duy trì trong nhiều tuần?</h3><p>Chọn khung giờ học viên còn đủ năng lượng, không chỉ chọn giờ trống.</p></article><article><Star size={28}/><span>MỤC TIÊU</span><h3>Làm sao mô tả mục tiêu để gia sư hiểu nhanh?</h3><p>Nêu phần đang yếu, kết quả mong muốn và mốc thời gian.</p></article></div></div></section>
    <section className="public-final public-final--learner"><div className="public-wrap"><span>BẮT ĐẦU TỪ 4 THÔNG TIN</span><h2>Môn học. Khu vực. Lịch rảnh. Mức phí.</h2><p>Đó là đủ để bạn thu hẹp lựa chọn phù hợp hơn.</p><DemoLink to="/learner/search" className="public-btn--yellow">Tìm gia sư ngay</DemoLink></div></section>
  </main><PublicFooter/>{dialog && <PublicDialog {...dialog} onClose={() => setDialog(null)}>{dialog.tutorId && <div className="public-dialog__links"><Link to={`/tutors/${dialog.tutorId}`}>Xem trang hồ sơ</Link><Link to={`/requests/new?tutor=${dialog.tutorId}`}>Tạo yêu cầu học demo</Link></div>}</PublicDialog>}</div>;
}
