import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BadgeCheck, CalendarDays, Check, CircleDollarSign, Clock3, MapPin, ShieldCheck, SlidersHorizontal, Sparkles } from 'lucide-react';
import { PublicDialog, PublicFooter, PublicHeader, SectionHead } from './PublicChrome.jsx';
import { DemoLink } from './PublicPieces.jsx';
import { money, photo, publicRequests } from '../../data/public.js';

const slots = ['T2 tối', 'T3 tối', 'T4 chiều', 'T5 tối', 'T6 chiều', 'T7 sáng', 'CN sáng'];

export default function TutorLanding() {
  const [subject, setSubject] = useState('Tất cả môn');
  const [area, setArea] = useState('Tất cả khu vực');
  const [time, setTime] = useState('Mọi khung giờ');
  const [minFee, setMinFee] = useState('0');
  const [sort, setSort] = useState('fit');
  const [fee, setFee] = useState(200000);
  const [sessions, setSessions] = useState(4);
  const [selectedSlots, setSelectedSlots] = useState(['T3 tối','T5 tối','T7 sáng']);
  const [dialog, setDialog] = useState(null);
  const filtered = useMemo(() => publicRequests.filter((r) => (subject === 'Tất cả môn' || r.subject === subject) && (area === 'Tất cả khu vực' || r.area === area) && (time === 'Mọi khung giờ' || r.time === time) && r.fee >= Number(minFee)).sort((a,b) => sort === 'fee' ? b.fee-a.fee : sort === 'recent' ? publicRequests.indexOf(a)-publicRequests.indexOf(b) : b.fit-a.fit), [subject,area,time,minFee,sort]);
  const toggleSlot = (slot) => setSelectedSlots((items) => items.includes(slot) ? items.filter((x) => x !== slot) : [...items, slot]);
  const show = (title,text) => setDialog({title,text});
  return <div className="public-page public-page--tutor"><PublicHeader kind="tutor" onInfo={show}/><main>
    <section className="public-hero public-hero--tutor"><div className="public-wrap public-hero__grid"><div className="public-hero__copy"><span className="public-hero__eyebrow">TUTORNEARME FOR TUTORS</span><h1>Biến kiến thức của bạn thành những <em>buổi học có giá trị.</em></h1><p>Chọn yêu cầu theo môn, khu vực, lịch và ngân sách. Chủ động quyết định nhận lớp, mức phí và thông tin nào xuất hiện trên hồ sơ của bạn.</p><div className="public-hero__actions"><DemoLink to="/tutor/profile" className="public-btn--yellow">Tạo hồ sơ gia sư</DemoLink><a className="public-hero__text-link" href="#profile">Xem cách tạo hồ sơ ↘</a></div><div className="public-hero__proof"><span><BadgeCheck size={18}/> Thông tin rõ ràng</span><span><CalendarDays size={18}/> Chủ động lịch dạy</span></div></div><div className="public-hero__visual"><img className="public-hero__photo-main" src={photo.tutorHero} alt="Sinh viên đang hướng dẫn học tập"/><img className="public-hero__photo-side" src={photo.tutorSide} alt="Buổi học nhóm với gia sư"/><span className="public-float public-float--yellow"><b>Rõ ràng</b><small>lớp học · lịch · mức phí</small></span><span className="public-float public-float--location"><b>YÊU CẦU MỚI</b><small>Toán · Bình Thạnh</small></span></div></div></section>
    <section className="public-section public-tutor-setup" id="setup"><div className="public-wrap"><div className="public-tutor-setup__title"><b>01</b><div><span className="public-kicker">LỌC CƠ HỘI THEO TIÊU CHÍ CỦA BẠN</span><h2>Bạn muốn nhận lớp như thế nào?</h2></div></div><div className="public-tutor-setup__fields"><label>Môn học<select value={subject} onChange={(e) => setSubject(e.target.value)}><option>Tất cả môn</option><option>Toán</option><option>Tiếng Anh</option><option>Vật lý</option><option>IELTS</option></select></label><label>Khu vực<select value={area} onChange={(e) => setArea(e.target.value)}><option>Tất cả khu vực</option><option>Bình Thạnh</option><option>Thủ Đức</option><option>Quận 3</option><option>Phú Nhuận</option></select></label><label>Thời gian<select value={time} onChange={(e) => setTime(e.target.value)}><option>Mọi khung giờ</option><option>Buổi chiều</option><option>Buổi tối</option><option>Cuối tuần</option></select></label><label>Mức phí từ<select value={minFee} onChange={(e) => setMinFee(e.target.value)}><option value="0">Không giới hạn</option><option value="200000">200.000đ / buổi</option><option value="250000">250.000đ / buổi</option></select></label><a href="#opportunities" className="public-btn public-btn--yellow"><SlidersHorizontal size={17}/> Xem cơ hội</a></div></div></section>
    <section className="public-section public-opportunities" id="opportunities"><div className="public-wrap"><div className="public-results-head"><SectionHead kicker="NHU CẦU ĐANG CHỜ" title="Nhìn nhanh trước khi quyết định nhận lớp." text="Mỗi yêu cầu gom môn học, khu vực, thời gian và ngân sách để bạn đánh giá."/><div className="public-results-head__tools"><span>{filtered.length} yêu cầu phù hợp</span><label>Sắp xếp<select value={sort} onChange={(e) => setSort(e.target.value)}><option value="fit">Phù hợp</option><option value="fee">Mức phí cao</option><option value="recent">Mới nhất</option></select></label></div></div>{filtered.length ? <div className="public-request-grid">{filtered.map((request) => <article className="public-request-card" key={request.id}><div className="public-request-card__top"><span>{request.subject}</span><small>{request.age}</small></div><h3>{request.title}</h3><div className="public-request-card__facts"><span><MapPin size={16}/>{request.area}</span><span><Clock3 size={16}/>{request.time}</span><span><BadgeCheck size={16}/>{request.fit}% phù hợp</span></div><div className="public-request-card__bottom"><strong>{money(request.fee)}đ <small>/ buổi</small></strong><button type="button" onClick={() => show(request.title, `${request.subject} · ${request.area} · ${request.time}. Đây là yêu cầu minh họa; vào không gian gia sư để xem trạng thái xử lý.`)}>Xem yêu cầu <ArrowRight size={16}/></button></div></article>)}</div> : <div className="public-empty"><h3>Chưa có yêu cầu khớp bộ lọc</h3><p>Thử nới rộng khu vực, môn học hoặc mức phí.</p><button className="public-btn public-btn--blue" onClick={() => { setSubject('Tất cả môn'); setArea('Tất cả khu vực'); setTime('Mọi khung giờ'); setMinFee('0'); }}>Xóa bộ lọc</button></div>}<div className="public-section__end"><DemoLink to="/tutor/requests" className="public-btn--outline-blue">Xem danh sách yêu cầu demo</DemoLink></div></div></section>
    <section className="public-section public-tutor-income" id="income"><div className="public-wrap public-tutor-income__grid"><div><SectionHead kicker="CHỦ ĐỘNG MỨC PHÍ" title="Ước tính thu nhập tháng theo lịch dạy của bạn." text="Chọn mức phí và số buổi có thể dạy mỗi tuần để hình dung doanh thu gộp tham khảo. Đây không phải cam kết thu nhập." light/><div className="public-tutor-income__mini"><CircleDollarSign size={24}/> Bạn luôn quyết định mức phí và thời gian dạy.</div></div><div className="public-calculator"><label>Mức phí mỗi buổi <strong>{money(fee)}đ</strong><input type="range" min="100000" max="400000" step="10000" value={fee} onChange={(e) => setFee(Number(e.target.value))}/></label><label>Số buổi mỗi tuần <strong>{sessions} buổi</strong><input type="range" min="1" max="10" value={sessions} onChange={(e) => setSessions(Number(e.target.value))}/></label><div className="public-calculator__result"><span>Ước tính mỗi tháng <small>4 tuần · doanh thu gộp</small></span><strong>{money(fee * sessions * 4)}đ</strong></div><small>Con số minh họa, chưa tính thay đổi lịch hoặc chi phí khác.</small></div></div></section>
    <section className="public-section public-tutor-profile" id="profile"><div className="public-wrap"><SectionHead kicker="HỒ SƠ CHUYÊN MÔN" title="Tạo hồ sơ gia sư trong 3 bước rõ ràng." text="Cho người học thấy điều bạn có thể hỗ trợ trước khi họ gửi yêu cầu."/><div className="public-tutor-profile__steps">{[['01','Giới thiệu chuyên môn','Môn học, kinh nghiệm và cách bạn hỗ trợ học viên.'],['02','Chọn khu vực & lịch','Đánh dấu những thời điểm bạn thực sự có thể dạy.'],['03','Xem trước & gửi','Kiểm tra thông tin hiển thị trên hồ sơ demo.']].map(([n,title,text]) => <div key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div><div className="public-tutor-profile__lower"><div className="public-availability"><div><span className="public-kicker">LỊCH DẠY CỦA BẠN</span><h3>Chọn khung giờ có thể nhận lớp</h3><p>Chạm để bật/tắt lịch rảnh trong giao diện minh họa.</p></div><div className="public-availability__slots">{slots.map((slot) => <button type="button" aria-pressed={selectedSlots.includes(slot)} className={selectedSlots.includes(slot) ? 'is-selected' : ''} key={slot} onClick={() => toggleSlot(slot)}>{selectedSlots.includes(slot) && <Check size={15}/>} {slot}</button>)}</div><small>{selectedSlots.length} khung giờ đã chọn</small></div><div className="public-privacy-card"><ShieldCheck size={36}/><span className="public-kicker">QUYỀN RIÊNG TƯ</span><h3>Thông tin cá nhân được bảo mật nghiêm ngặt.</h3><p>Prototype chỉ minh họa hồ sơ ở mức cần thiết. Bạn có thể xem trước những gì được hiển thị.</p><button type="button" onClick={() => show('Quyền riêng tư hồ sơ', 'Địa chỉ nhà và số điện thoại không hiển thị công khai trong giao diện minh họa.')}>Xem chi tiết <ArrowRight size={16}/></button></div></div></div></section>
    <section className="public-final public-final--tutor"><div className="public-wrap public-final__row"><div><span>BẮT ĐẦU RÕ RÀNG, CHỦ ĐỘNG</span><h2>Sẵn sàng chọn lớp phù hợp?</h2><p>Xem trước cách hồ sơ hiển thị, mức phí và quyền riêng tư.</p></div><DemoLink to="/tutor/profile" className="public-btn--yellow">Tạo hồ sơ gia sư</DemoLink></div></section>
  </main><PublicFooter/>{dialog && <PublicDialog {...dialog} onClose={() => setDialog(null)}><div className="public-dialog__links"><Link to="/tutor/dashboard">Mở dashboard gia sư</Link><Link to="/tutor/requests">Xem yêu cầu</Link></div></PublicDialog>}</div>;
}
